version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-devops-pgp
hooks:
  BeforeInstall:
    - location: scripts/boot
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
